### ISSUE TITLE
Unable to create an account

### ISSUE THREAD

**Issue by miahuynhh** [JDKaim/HuskySwap#23]
* I followed the set up steps and was able to see the login and signup page on localhost:4200
* However, I'm getting this error when pressing "Register" on the signup page
<img width="1413" alt="Screenshot 2024-11-19 at 3 17 11 PM" src="https://github.com/user-attachments/assets/b8564033-b52f-4184-8977-1b123cd4ebec">

* My backend terminal looks like this after the running the last instructed command `dotnet run --project LightNap.WebApi`
<img width="881" alt="Screenshot 2024-11-19 at 3 18 57 PM" src="https://github.com/user-attachments/assets/60a08ffc-c83c-4848-9ed2-f98b80da7f5c">

* My frontend terminal looks like this after running the last instructed command `npm run start`
<img width="875" alt="Screenshot 2024-11-19 at 3 20 03 PM" src="https://github.com/user-attachments/assets/0c10b89a-c6d8-43b8-8546-81d62a932620">

**Comment by CatherineXJJin** [comment]
I'm also experiencing this error, with the same error message
![Screenshot 2024-11-19 164828](https://github.com/user-attachments/assets/b8544e57-84aa-4fed-aebe-76cfc8b11a5c)

**Comment by miahuynhh** [comment]
even after downgrading to .NET version 8.0.404 as described in Issue #24 , I get the same error message that the server wouldn't connect. 
<img width="816" alt="Screenshot 2024-11-19 at 9 08 03 PM" src="https://github.com/user-attachments/assets/9483d5d0-949b-4c4f-a700-fcaf5cd385c4">

**Comment by JDKaim** [comment]
Based on the screenshots, it appears that the backend was not running. The error message "We were unable to connect to the service" is sent by the frontend when it is unable to connect to the backend. Please try running the backend in a separate terminal when running the frontend and let us know if the same issues still persist.
