### ISSUE TITLE
Need to download a specific version of dotnet in order to run everything 

### ISSUE THREAD

**Issue by kirupanandhini** [JDKaim/HuskySwap#24]
Summary: (Update documentation to specify dotnet version to download)
I downloaded the latest version of dotnet, and was unable to build the backend since as it required dotnet version 8.0.x. I resolved by uninstalling and reinstalling the correct version (and I did this before I copied the errors, which is why I am unable to paste them here).  

Component:
Backend projects 

Version:
Beta release

Device, OS, Browser:
Macbook Pro, Mac OS, Chrome

Description:
The latest version of dotnet (version 9) does not seem compatible with the project. It's not a major issue as I imagine most developers would see the message and downgrade, but it would be good to specify in the developer guide.

**Comment by JDKaim** [comment]
This code should still build in dotnet 9, we are unable to reproduce this issue. I just tried to reproduce this, and was able to run the backend in .NET 9.
