### ISSUE TITLE
Having trouble logging in as Admin 

### ISSUE THREAD

**Issue by kirupanandhini** [JDKaim/HuskySwap#26]
I received the Admin credentials but am unable to log in. Would there be a way for me to confirm I have the right credentials? 
<img width="1440" alt="Screenshot 2024-11-19 at 4 30 04 PM" src="https://github.com/user-attachments/assets/02ca06a5-e321-4af5-b545-03cbf9c1be0b">

**Comment by JDKaim** [comment]
Thank you for raising this, there was a typo in the admin password originally posted, and it has since been fixed.
