### ISSUE TITLE
Awkward Setting Button and Sidebar Toggle Button location

### ISSUE THREAD

**Issue by laurenyarrington** [JDKaim/HuskySwap#28]
Summary: (Enhancement/Suggestion)
The setting button in the middle of the right side of the homepage is awkwardly placed, as is the sidebar toggle on the top bar. 

Component:
Frontend pages (Home page)

Version:
Beta release

Device, OS, Browser:
MacBook Pro; MacOS; Chrome 

Description:
The Setting Gear button placed in the center of the right side of the screen is awkwardly placed. It could be cleaner to place in one of the corners of the screen. The same goes for the Sidebar Toggle button. I think the toggle button and HuskySwap icon and title could be switched so that the toggle is in the corner and the HuskySwap icon is centered. Not a big issue or time-sensitive but it could improve the homepage layout.

**Comment by JDKaim** [comment]
Thank you, this is good feedback and we will consider it for VNext.
